version: '3'
services:
  #db:
    #image: mariadb:10.2
    #environment:
      #MYSQL_DATABASE: test
      #MYSQL_ROOT_PASSWORD: test
    #ports:
      #- 3306:3306
  space-mgt:
    image: adenijiazeez/space-management-system:latest
    ports:
      - 5000:5000